### PR TITLE
LPS-134015 Update themeDisplay user when persistState is true in order to generate the proper language prefix afterwards

### PR DESCRIPTION
**Pull request by dacousalr**
Hi @jgarcialr, I have added a new commit regarding the version I showed you in PTR-2481. Could you please review it taking into account the customer context? If you do not see any objection, please, submit it to Eric Yan or somebody from Core Infra for final review. Thanks in advance

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:bundle

**Pull request closed without merging**
